/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.cruftbusters

import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.shouldBe

class LibraryTest : FunSpec({
  test("someLibraryMethodReturnsTrue") {
    val classUnderTest = Library()
    classUnderTest.someLibraryMethod() shouldBe true
  }
})
